### ISSUE TITLE
Ramming kills cause duplicate entries in observer kill feed

### ISSUE THREAD

**Issue by SiriusTR** [dxx-redux/dxx-redux#10]
Note from Observatory (reportedly some folks have seen this already though). If someone gets a ramming kill, reportedly the kill feed in the top-right shows it twice. Doesn't report twice to the tracker though; only really affects the UI. Might have something to do with how player-player collision damage is processed.

**Comment by arbruijn** [comment]
https://www.twitch.tv/videos/1813216823?t=0h27m36s

Looks like this happens because multi_send_damage keeps sending damage events while in the death sequence. For weapons this is prevented with a Player_is_dead check in collide_player_and_weapon, but not for other damage events.

I think the proper fix is adding this line to the top of multi_send_damage:
`if (Player_is_dead || ConsoleObject->flags & OF_SHOULD_BE_DEAD) { return; }`
(flags check in case there are multiple damage events in the same frame)
